// modules/svg-assets.ts
import { defineNuxtModule, createResolver, addComponent, addTemplate, addTypeTemplate, updateTemplates } from '@nuxt/kit'
import { defu } from 'defu'
import { readdirSync, lstatSync, readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

declare module 'nuxt/schema' {
  interface PublicRuntimeConfig {
    svgToIcon: {
      componentClassName: string
      iconsDir: string
      svgAssets?: Record<string, string>
    }
  }
}

const ICON_NAMES_TEMPLATE_FILENAME = 'nuxt-svg-to-icon-icon-names.d.ts'

function walkIcons(dir: string, onSvg: (key: string, fullPath: string) => void) {
  function walk(currentDir: string, prefix = '') {
    if (!existsSync(currentDir)) {
      return
    }
    try {
      const entries = readdirSync(currentDir)
      for (const entry of entries) {
        const fullPath = join(currentDir, entry)
        const stat = lstatSync(fullPath)
        const key = prefix ? `${prefix}/${entry}` : entry

        if (stat.isDirectory()) {
          walk(fullPath, key)
        }
        else if (entry.endsWith('.svg')) {
          onSvg(String(key).replace('.svg', ''), fullPath)
        }
      }
    }
    catch (e) {
      console.error('SVG module load path error: ', e)
    }
  }

  walk(dir)
}

function readSvgAssets(dir: string) {
  const svgs: Record<string, string> = {}

  walkIcons(dir, (name, fullPath) => {
    svgs[name] = String(readFileSync(fullPath, 'utf-8')).trim()
  })

  return svgs
}

function readIconNames(dir: string) {
  const names: string[] = []

  walkIcons(dir, (name) => {
    names.push(name)
  })

  return names
}

function generateIconNamesType(names: string[]) {
  const union = names.length
    ? names.map(name => JSON.stringify(name)).join(' | ')
    : 'string'

  return `// Generated by nuxt-svg-to-icon\nexport type IconName = ${union}\n`
}

export default defineNuxtModule({
  meta: {
    name: 'nuxt-svg-to-icon',
    configKey: 'nuxtSvgToIcon',
    compatibility: {
      nuxt: '>=3.0.0',
    },
  },
  defaults: {
    iconsDir: 'assets/icons',
    asyncComponent: false,
    componentName: 'NuxtIcon',
    componentClassName: 'nuxt-icon',
  },
  setup(options, nuxt) {
    const resolver = createResolver(import.meta.url)
    const assetsDir = join(nuxt.options.srcDir, options.iconsDir)

    nuxt.options.runtimeConfig = nuxt.options.runtimeConfig || {}
    nuxt.options.runtimeConfig.public = nuxt.options.runtimeConfig.public || {}
    nuxt.options.runtimeConfig.public.svgToIcon = defu(nuxt.options.runtimeConfig.public.svgToIcon, {
      componentClassName: options.componentClassName,
      iconsDir: options.iconsDir,
    })

    addTypeTemplate({
      filename: ICON_NAMES_TEMPLATE_FILENAME,
      getContents: () => generateIconNamesType(readIconNames(assetsDir)),
    })

    if (options.asyncComponent) {
      // import.meta.glob only accepts static patterns, so the glob for the
      // configured iconsDir is generated into a build template
      const globBase = '/' + options.iconsDir.replace(/\\/g, '/').replace(/^\/+|\/+$/g, '')

      addTemplate({
        filename: 'nuxt-svg-to-icon-glob.mjs',
        getContents: () => [
          `export const globBase = ${JSON.stringify(globBase)}`,
          `export const iconsGlob = import.meta.glob(${JSON.stringify(globBase + '/**/*.svg')}, { query: '?raw', import: 'default' })`,
          '',
        ].join('\n'),
      })

      addTypeTemplate({
        filename: 'nuxt-svg-to-icon-glob.d.ts',
        getContents: () => [
          `declare module '#build/nuxt-svg-to-icon-glob.mjs' {`,
          `  export const globBase: string`,
          `  export const iconsGlob: Record<string, () => Promise<string>>`,
          `}`,
          '',
        ].join('\n'),
      })

      addComponent({
        filePath: resolver.resolve('./runtime/components/async-icon-name.vue'),
        name: options.componentName,
        global: true,
      })
    }
    else {
      const generateIcons = () => {
        const svgAssets = readSvgAssets(assetsDir)
        nuxt.options.runtimeConfig.public.svgToIcon.svgAssets = svgAssets
      }

      generateIcons()

      addComponent({
        filePath: resolver.resolve('./runtime/components/icon-name.vue'),
        name: options.componentName,
        global: true,
      })

      nuxt.hooks.hook('builder:watch', (evt, dir) => {
        if (dir.includes(options.iconsDir)) {
          console.info('builder:watch', evt, dir)
          generateIcons()
          console.info('assets changes added')
        }
      })
    }

    nuxt.hooks.hook('builder:watch', (evt, dir) => {
      if (dir.includes(options.iconsDir)) {
        updateTemplates({ filter: template => template.filename === ICON_NAMES_TEMPLATE_FILENAME })
      }
    })
  },
})
